version: "2"
run:
  timeout: 10m10s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - unconvert
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

  # don't enable:
  #  - asciicheck
  #  - depguard
  #  - dogsled
  #  - dupl
  #  - funlen
  #  - gochecknoinits
  #  - gochecknoglobals
  #  - gocognit
  #  - goconst
  #  - gocritic
  #  - gocyclo
  #  - gomnd
  #  - godot
  #  - godox
  #  - goerr113
  #  - lll
  #  - prealloc
  #  - revive
  #  - stylecheck
  #  - staticcheck
  #  - structcheck
  #  - testpackage
  #  - unused
  #  - unparam
  #  - wsl