sudo: required
language: go
go: '1.11'
services:
- docker
install:
- make tools
script:
- make golint test
notifications:
  slack:
    secure: gcT0X7a9IU5lYlVlLmVJAIoDZfT6V81F0pLtNMeg2iHCN08Mcgw6xDePj9Yrxnpg/wEi9X+9cLeVBrXk5H/MB/CdtWBs94evwSyq62/v9F5BvU1/MYu7cPHzM1EnsPWXagePew+YnDGAqcXyOfhK0UMawW6lErJLcbsNZJw9VkZFF258HGpRXXWFvVRAbIN1KMfIMoRzbMNfvhBWUJv5wAUiZHElg7mnIJ0ZETsbferpCo7wzAztBy4EwUM+Tqhv7s0COz4fnIQyMPSv7bz9/lvVh7m+GlVnVDOoEiSOaVhg+U1UvyZSyx2N1mxlrgEFqrewXVz1c/L4E71yS3/JIdbdSmq4kEzgrjz61eYrwh2yqlewMLHB6FTctbplodXLWqZBEtuX2SvbPc8uhyBDW+egz2e1AZ9R65ChnG4HWaQ5ZI/hBi1YGgeENCdxlasJVHGYeSL+yeNOummkUdRa8GvRAEoJ8HdEeaAqO1do9F1645X5VfpD2bt8gIKi+B/RmgCTNwRSwI2q4yXcaFrT+yy0dd+Qcz/oOoyqQL+NbOm5gmQdSk8mE3l0uqM3CTQFo1xNp4yYl6byYlhOV3b+6xK3zFD0ogGZJ83Z8n0ecyZGUnDnJv6uJ4hCjV4kWNgvbtJ59QCJt3iGWbapgW53lwYD0H00DRmf4/tBVFIRLGE=
