FROM golang:alpine
MAINTAINER Kazumichi Yamamoto <yamamoto.febc@gmail.com>

RUN set -x && apk add --no-cache --virtual .build_deps bash git make zip 

ADD . /go/src/github.com/sacloud/packer-builder-sakuracloud

WORKDIR /go/src/github.com/sacloud/packer-builder-sakuracloud
CMD ["make"]
