FROM hashicorp/packer:full
MAINTAINER Kazumichi Yamamoto <yamamoto.febc@gmail.com>

RUN set -x && apk add --no-cache --virtual .build_deps make zip
RUN go get -u github.com/kardianos/govendor

ADD . /go/src/github.com/sacloud/packer-builder-sakuracloud
WORKDIR /go/src/github.com/sacloud/packer-builder-sakuracloud
RUN make install

VOLUME ["/work"]
WORKDIR /work
ENTRYPOINT ["/go/bin/packer"]
CMD ["--help"]
