name: Release
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
env:
  GOPROXY: https://proxy.golang.org
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup tools
        run: make tools

      - name: make build-x
        run: make build-x

      - name: make release
        run: make release
